In [1]:
from astropy.table import Table
import numpy as np
from collections import Counter
%matplotlib inline

In [1]:
# movies=Table.read('movies.dat', format='ascii', delimiter='::', guess=False) 
# #print len (t['12+log(O/H)'])
# #metallicities=t['12+log(O/H)']

# #movies (genre, title, production year)
# ratings=Table.read('ratings.dat', format='ascii', delimiter='::', guess=False) 
# users=Table.read('users.dat', format='ascii', delimiter='::', guess=False) 
# #users (gender, age, occupation)

#ratings=read_data("ratings.dat")
ratings=[]
r = open('ratings.dat', 'r')
for line in r:
    data_r = line.split('::')
    ratings.append([int(z) for z in data_r[:2]])
r.close()


movies=[]
m = open('movies.dat', 'r')
for line in m:
    #print line
    data_m = line.split('::')
    movies.append([int(z) for z in data_m[:2]])
m.close()


users=[]
u = open('users.dat', 'r')
for line in u:
    data_u = line.split('::')
    users.append([int(z) for z in data_u[:2]])
u.close()

#ratings= user,movie,rating

ValueError: invalid literal for int() with base 10: 'Toy Story (1995)'

In [15]:
print np.mean(ratings[:,-1])
print 

3.58156445303


In [20]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
#load data
#ratings=read_data("ratings.dat")
ratings=[]
f = open("ratings.dat", 'r')
for line in f:
    data = line.split('::')
    ratings.append([int(z) for z in data[:3]])
f.close()
ratings=np.array(ratings)

"""
Alternatively, instead of reading data file line by line you could use the Numpy
genfromtxt() function. For example:

ratings = np.genfromtxt("ratings.dat", usecols=(0, 1, 2), delimiter='::', dtype='int')

will create an array with 3 columns.

Additionally, you may now save the rating matrix into a binary file 
and later reload it very quickly: study the np.save and np.load functions.
"""


#split data into 5 train and test folds
nfolds=5

#allocate memory for results:
err_train=np.zeros(nfolds)
err_test=np.zeros(nfolds)
mae_train=np.zeros(nfolds)
mae_test=np.zeros(nfolds)
#to make sure you are able to repeat results, set the random seed to something:
np.random.seed(17)

seqs=[x%nfolds for x in range(len(ratings))]
#print np.shape(seqs)
np.random.shuffle(seqs)

#for each fold:
for fold in range(nfolds):
    train_sel=np.array([x!=fold for x in seqs])
    test_sel=np.array([x==fold for x in seqs])
    train=ratings[train_sel]
    test=ratings[test_sel]
#     print len(train)
#     print len(test)

    df = pd.DataFrame(ratings)



#     reg = linear_model.LinearRegression()
#     reg.fit (train,test)
#     print(reg.coef_)
#     print(reg.intercept_)
#calculate model parameters: mean rating over the training set:
gmr=np.mean(train[:,2])

#apply the model to the train set:
err_train[fold]=np.sqrt(np.mean((train[:,2]-np.mean(gmr))**2))

mae_train[fold]=np.mean(np.abs(train[:,2]-np.mean(gmr)))
#apply the model to the test set:
err_test[fold]=np.sqrt(np.mean((test[:,2]-np.mean(gmr))**2))
mae_test[fold]=np.mean(np.abs(train[:,2]-np.mean(gmr)))

#print errors:
#     print("Fold " + str(fold) + ": RMSE_train=" + str(err_train[fold]) + "; RMSE_test=" + str(err_test[fold]))

# #print the final conclusion:
# print("\n")
# print("Mean error on TRAIN: " + str(np.mean(err_train)))
# print("Mean error on  TEST: " + str(np.mean(err_test)))
# print ("Mean abs error on TRAIN:" + str(np.mean(mae_train)))
# print ("Mean abs error on TEST:" + str(np.mean(mae_test)))
# Just in case you need linear regression: help(np.linalg.lstsq) will tell you 
# how to do it!

In [198]:
####Each user rating average
all_u=[]
un_numbers=len((set(ratings[:,0])))
un_numbers=np.arange(1,un_numbers+1)

c=Counter(ratings[:,0])
for i in un_numbers:
    num_ratings=c[i]
    #print num_ratings
#     print num_ratings
    
    #print(np.mean(ratings[:,2][0:num_ratings]))
    all_u.append(np.mean(ratings[:,2][np.where(ratings[:,0]==i)[0][0]:np.where(ratings[:,0]==i)[0][0]+num_ratings]))
all_urms=np.sqrt((all_u-np.mean(ratings[:,2]))**2)
print np.nanmean(all_urms)

0.356596391897


In [142]:
#####Each movie rating average

un_numbers=len((set(ratings[:,1])))
un_numbers=np.arange(1,un_numbers+1)
# user_id=ratings[:,0]
# rate=ratings[:,2]
# dict_list = zip(user_id,rate)
# dict_list=dict(dict_list)
# print len(dict_list)
#print un_number
all_m=[]
c=Counter(ratings[:,1])
for i in un_numbers:
    num_ratings=c[i]
    #print num_ratings
#     print num_ratings
    
    #print(np.mean(ratings[:,2][0:num_ratings]))
    #all_m.append(np.mean(ratings[:,2][np.where(ratings[:,1]==i)[0][0]:np.where(ratings[:,1]==i)[0][0]+num_ratings]))
#     print np.where(ratings[:,1]==i)[0][0],np.where(ratings[:,1]==i)[0][0]+num_ratings
all_mrms=np.sqrt((all_m-np.mean(ratings[:,2]))**2)

# print np.nanmean(all_mrms)

40 2117
839 1540
3406 3884
583 753
3408 3704
297 1237
842 1300
10127 10195
9649 9751
1395 2283
2943 3976
11645 11805
5452 5551
651 804
6896 7042
387 1069
501 1336
7812 7969
6901 7290
15680 15840
148 1504
7835 8213
7243 7369
421 1045
677 1657
2073 2173
29270 29331
4235 4414
426 829
1823 1897
25666 25807
442 1953
138787 138791
447 2198
6315 6385
450 1378
75509 75517
3564 3592
257 1619
9966 9996
278 520
566 787
10030 10196
2120 2431
3016 3560
5478 5644
283 1420
25 407
51209 51236
303 2086


IndexError: index 0 is out of bounds for axis 0 with size 0

In [212]:
import numpy as np
import pandas as pd 

#load data
#ratings=read_data("ratings.dat")
ratings=[]
f = open("ratings.dat", 'r')
for line in f:
    data = line.split('::')
    ratings.append([int(z) for z in data[:3]])
f.close()
ratings=np.array(ratings)



#####Each movie rating average

####converting dataset to dataframe 
df = pd.DataFrame(ratings)

##calculating the mean of each movie id 
c =df.groupby(1, as_index=False)[2].mean()
dfm = c[2]
dfm.fillna(gmr)
print np.mean(dfm)
movie_column = np.array(dfm)
all_urms=np.sqrt((movie_column-np.mean(ratings[:,2]))**2) 

df = pd.DataFrame(ratings)


###starting if the folds 
df = pd.DataFrame(train)
train_1 = df.groupby(0, as_index=False)[2].mean()
# print train_1


dff = pd.DataFrame(test)
test_1 = dff.groupby(0, as_index=False)[2].mean()
# print len(test_1)



#####

3.23889217791


In [205]:
print np.mean(all_urms)

0.572515096735


In [215]:

c=df.groupby(0, as_index=False)[2].mean()
dfu=c[2]
dfu.fillna(gmr)
print np.mean(dfu)


3.702704867


In [218]:
np.abs(np.mean((train[:,2]-np.mean(dfu))))

0.12055461855190017

In [7]:
from sklearn import linear_model

reg = linear_model.LinearRegression()
#reg.fit (ratings[:,2][0:200],ratings[:,2][200:400])
print np.shape(ratings[:,2][0:200])
print np.shape(ratings[:,2][0:200])
print(reg.coef_)
print(reg.intercept_)

(200,)
(200,)


AttributeError: 'LinearRegression' object has no attribute 'coef_'

200
200


In [273]:

reg = linear_model.LinearRegression()
reg.fit (train,test[1:])
print(reg.coef_)
print(reg.intercept_)

print reg.coef_[0][0]*np.mean(dfu) +reg.coef_[0][1]*np.mean(dfm) +reg.coef_[0][2]


[[  9.99979105e-01  -8.85269148e-06  -6.19996902e-02]
 [ -1.03180213e-02   5.97731349e-03  -2.49239120e-01]
 [  7.80987289e-06   2.30425627e-06   5.33463777e-02]]
[ -9.85262480e-01   1.88644158e+03   3.36219747e+00]
3.64059913424


In [262]:
print (reg.coef_)[0]

[  9.99979105e-01  -8.85269148e-06  -6.19996902e-02]


In [16]:
x=np.array([2,2,3,5,3])*1.0
print x

[ 2.  2.  3.  5.  3.]


In [53]:
print ratings/1.0
ratings[2,2]=48.77
print ratings[2,2]

[[  1.00000000e+00   1.19300000e+03   2.26000000e+02]
 [  1.00000000e+00   6.61000000e+02   2.26000000e+02]
 [  1.00000000e+00   9.14000000e+02   4.80000000e+01]
 ..., 
 [  6.04000000e+03   5.62000000e+02   5.00000000e+00]
 [  6.04000000e+03   1.09600000e+03   4.00000000e+00]
 [  6.04000000e+03   1.09700000e+03   4.00000000e+00]]
48
